"""Edit Cart

Revision ID: 021004c653aa
Revises: 807f4be82317
Create Date: 2025-06-08 15:52:14.937195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '021004c653aa'
down_revision: Union[str, None] = '807f4be82317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pizza_cart_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_variant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['cart_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_item_ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cart_item_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cart_item_id'], ['pizza_cart_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('cart_items_product_variant_id_fkey', 'cart_items', type_='foreignkey')
    op.drop_constraint('cart_items_user_id_fkey', 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cart_items', 'product_variants', ['product_variant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key('cart_items_user_id_fkey', 'cart_items', 'users', ['user_id'], ['id'])
    op.create_foreign_key('cart_items_product_variant_id_fkey', 'cart_items', 'product_variants', ['product_variant_id'], ['id'])
    op.drop_table('cart_item_ingredients')
    op.drop_table('pizza_cart_items')
    # ### end Alembic commands ###
