"""edit type

Revision ID: 233b4ce805b0
Revises: ef09d69cc3eb
Create Date: 2025-05-16 12:00:20.608029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '233b4ce805b0'
down_revision: Union[str, None] = 'ef09d69cc3eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  op.execute("ALTER TABLE products ALTER COLUMN type TYPE INTEGER USING ("
             "CASE type "
             "WHEN 'GROUP' THEN 0 "
             "WHEN 'CONSTRUCTOR' THEN 1 "
             "WHEN 'PIZZA' THEN 2 "
             "END)")
  op.execute("DROP TYPE type")  # удаляем ENUM, если больше не нужен

  # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'type',
               existing_type=sa.Integer(),
               type_=postgresql.ENUM('GROUP', 'CONSTRUCTOR', 'PIZZA', name='type'),
               existing_nullable=False)
    # ### end Alembic commands ###
