"""add quantity to cart_item_ingredients

Revision ID: 2f6f9273dee2
Revises: 50e6df7db900
Create Date: 2025-06-09 15:58:24.581546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '2f6f9273dee2'
down_revision: Union[str, None] = '50e6df7db900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_item_ingredients', sa.Column('quantity', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_cart_item_ingredient', 'cart_item_ingredients', ['cart_item_id', 'ingredient_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cart_item_ingredient', 'cart_item_ingredients', type_='unique')
    op.drop_column('cart_item_ingredients', 'quantity')
    # ### end Alembic commands ###
