"""add mapper_args to CartItem, PizzaCartItem add add type CartItem

Revision ID: 3f269f5a8c43
Revises: 2f6f9273dee2
Create Date: 2025-06-10 18:49:09.850951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '3f269f5a8c43'
down_revision: Union[str, None] = '2f6f9273dee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'type')
    # ### end Alembic commands ###
