"""remove none in overlay_image in ingredients

Revision ID: 48b746d4f600
Revises: e7dde7e0b464
Create Date: 2025-06-01 10:58:46.559385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '48b746d4f600'
down_revision: Union[str, None] = 'e7dde7e0b464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredients', 'overlay_image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredients', 'overlay_image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
