"""Add dough to pizza_cart_items

Revision ID: 50e6df7db900
Revises: 021004c653aa
Create Date: 2025-06-09 01:12:04.976790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '50e6df7db900'
down_revision: Union[str, None] = '021004c653aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pizza_cart_items', sa.Column('dough', sa.Enum('THICK_DOUGH', 'THIN_DOUGH', name='cart_dough', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pizza_cart_items', 'dough')
    # ### end Alembic commands ###
