"""Add CASCADE to PizzaIngredient

Revision ID: 807f4be82317
Revises: 8f8db4491b4d
Create Date: 2025-06-07 13:35:40.238970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '807f4be82317'
down_revision: Union[str, None] = '8f8db4491b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pizza_ingredients_ingredient_id_fkey', 'pizza_ingredients', type_='foreignkey')
    op.create_foreign_key(None, 'pizza_ingredients', 'ingredients', ['ingredient_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pizza_ingredients', type_='foreignkey')
    op.create_foreign_key('pizza_ingredients_ingredient_id_fkey', 'pizza_ingredients', 'ingredients', ['ingredient_id'], ['id'])
    # ### end Alembic commands ###
