"""change orders

Revision ID: 8b84f7434341
Revises: 4c97f840da7b
Create Date: 2025-06-14 00:50:06.797123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b84f7434341'
down_revision: Union[str, None] = '4c97f840da7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_item_ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('order_items', sa.Column('product_name', sa.String(), nullable=False))
    op.add_column('order_items', sa.Column('variant_size', sa.String(), nullable=False))
    op.add_column('order_items', sa.Column('type', sa.String(), nullable=False))
    op.add_column('order_items', sa.Column('dough', sa.Enum('THICK_DOUGH', 'THIN_DOUGH', name='dough'), nullable=True))
    # op.alter_column('orders', 'payment_method',
    #            existing_type=postgresql.ENUM('CASH', 'ELECTRONIC', name='payment_method_enum'),
    #            type_=sa.Enum('CASH', 'ELECTRONIC', name='paymentmethod'),
    #            existing_nullable=False)
    op.drop_constraint('orders_store_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_store_id_fkey', 'orders', 'stores', ['store_id'], ['id'], ondelete='SET NULL')
    op.alter_column('orders', 'payment_method',
               existing_type=sa.Enum('CASH', 'ELECTRONIC', name='paymentmethod'),
               type_=postgresql.ENUM('CASH', 'ELECTRONIC', name='payment_method_enum'),
               existing_nullable=False)
    op.drop_column('order_items', 'dough')
    op.drop_column('order_items', 'type')
    op.drop_column('order_items', 'variant_size')
    op.drop_column('order_items', 'product_name')
    op.drop_table('order_item_ingredients')
    # ### end Alembic commands ###
