"""Add CASCADE on pizza_ingredients.pizza_id

Revision ID: 8f8db4491b4d
Revises: 48b746d4f600
Create Date: 2025-06-07 11:34:43.949545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '8f8db4491b4d'
down_revision: Union[str, None] = '48b746d4f600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pizza_ingredients_pizza_id_fkey', 'pizza_ingredients', type_='foreignkey')
    op.create_foreign_key(None, 'pizza_ingredients', 'pizzas', ['pizza_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pizza_ingredients', type_='foreignkey')
    op.create_foreign_key('pizza_ingredients_pizza_id_fkey', 'pizza_ingredients', 'pizzas', ['pizza_id'], ['id'])
    # ### end Alembic commands ###
