"""edit ingredients

Revision ID: c068298c876d
Revises: a29aee5936f3
Create Date: 2025-05-26 10:48:15.315122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'c068298c876d'
down_revision: Union[str, None] = 'a29aee5936f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'is_deleted')
    op.add_column('pizza_ingredients', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pizza_ingredients', 'is_deleted')
    op.add_column('ingredients', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_table('pointcloud_formats',
    sa.Column('pcid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('schema', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint('pc_schemaisvalid(schema)', name='pointcloud_formats_schema_check'),
    sa.CheckConstraint('pcid > 0 AND pcid < 65536', name='pointcloud_formats_pcid_check'),
    sa.PrimaryKeyConstraint('pcid', name='pointcloud_formats_pkey')
    )
    op.create_table('us_lex',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('seq', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('word', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stdword', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_custom', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_us_lex')
    )
    op.create_table('us_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rule', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_custom', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_us_rules')
    )
    op.create_table('us_gaz',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('seq', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('word', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stdword', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_custom', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_us_gaz')
    )
    # ### end Alembic commands ###
