"""add order pickup store and fix cart items

Revision ID: c9e98e6e6470
Revises: 80f516d7b801
Create Date: 2025-06-13 15:21:43.525582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'c9e98e6e6470'
down_revision: Union[str, None] = '80f516d7b801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'price_per_item',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.add_column('orders', sa.Column('store_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'orders', 'stores', ['store_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('pizza_cart_items_product_variant_id_fkey', 'pizza_cart_items', type_='foreignkey')
    op.drop_column('pizza_cart_items', 'product_variant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pizza_cart_items', sa.Column('product_variant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('pizza_cart_items_product_variant_id_fkey', 'pizza_cart_items', 'product_variants', ['product_variant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'store_id')
    op.alter_column('order_items', 'price_per_item',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
