"""Initial

Revision ID: e6dc97b0d0f3
Revises: 
Create Date: 2025-05-11 22:00:14.914217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6dc97b0d0f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('point', Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('role', postgresql.ENUM('USER', 'COURIER', 'COOK', 'MANAGER', 'ADMIN', name='roles'), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('scores', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('stores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('start_working_hours', sa.Time(), nullable=False),
    sa.Column('end_working_hours', sa.Time(), nullable=False),
    sa.Column('start_delivery_time', sa.Time(), nullable=False),
    sa.Column('end_delivery_time', sa.Time(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('min_order_price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('area', Geometry(geometry_type='POLYGON', from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('point', Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('type', postgresql.ENUM('GROUP', 'PIZZA', 'CONSTRUCTOR', name='typecategory'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'position', name='uix_store_position')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    op.drop_table('stores')
    op.drop_table('users')
    op.drop_table('cities')
    # ### end Alembic commands ###
