"""add overlay_image in ingredients

Revision ID: e7dde7e0b464
Revises: 5c7e7bb48038
Create Date: 2025-06-01 10:51:35.104903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'e7dde7e0b464'
down_revision: Union[str, None] = '5c7e7bb48038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('overlay_image', sa.String(), nullable=True))
    op.alter_column('ingredients', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredients', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('ingredients', 'overlay_image')
    # ### end Alembic commands ###
